import type { Metadata } from 'next'
import LegalPageLayout from '../../components/legal/LegalPageLayout'

export const metadata: Metadata = {
  title: 'Privacy Policy · Prep by EVOLW',
  description: 'How Prep by EVOLW collects, handles, stores and protects your personal learning, resume, and authentication data.',
}

export default function PrivacyPage() {
  return (
    <LegalPageLayout
      title="Privacy Policy"
      subtitle="How we collect, store, process, and protect your information when using Prep by EVOLW."
      lastUpdated="September 2026"
      badge="Trust & Transparency"
    >
      <section className="legal-section">
        <h2>1. Entity and Scope</h2>
        <p>
          This Privacy Policy applies to the software platform &ldquo;Prep by EVOLW&rdquo; (&ldquo;Prep&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;), operated by{' '}
          <strong>Evolw Technologies</strong>, having its principal place of business in Bengaluru, Karnataka, India.
        </p>
        <p>
          This policy covers visitors, registered learners, and administrators accessing the website, platform APIs, and associated learning tools.
        </p>
      </section>

      <section className="legal-section">
        <h2>2. Information We Collect</h2>
        <p>We collect only the information necessary to provide structured technical interview preparation, progress tracking, and career workflows:</p>
        <ul>
          <li>
            <strong>Account and Authentication Credentials:</strong> Your name, email address, cryptographically salted and hashed passwords (for credential authentication), or OAuth account identifiers (if signing in with Google).
          </li>
          <li>
            <strong>Curriculum and Learning Records:</strong> Selected tracks, roadmap day schedules, task completions, revision dates, flashcards, personal notes, diagrams, and self-reported confidence ratings.
          </li>
          <li>
            <strong>Resume and Career Information:</strong> When voluntarily uploaded by the learner, raw resume text/PDF files, parsed skill evidence, employment history summaries, job preference filters, and target role categories.
          </li>
          <li>
            <strong>Mock Interview &amp; Assessment Evidence:</strong> Learner answers submitted during mock rounds, code editor snippets, diagram layouts, and rule-based feedback or weakness mappings generated by the platform.
          </li>
          <li>
            <strong>Payment and Transaction Records:</strong> Subscription and pass status, transaction IDs, payment interval, and receipt timestamps provided by our payment gateway. We do not process or store raw payment card numbers or banking passwords.
          </li>
          <li>
            <strong>Security and Technical Telemetry:</strong> Anonymized or pseudonymized IP addresses for abuse prevention, sliding-window rate limit counters, user agent strings, and structured error identifiers.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>3. How We Use and Process Data</h2>
        <p>We process collected data strictly for the following purposes:</p>
        <ul>
          <li>Generating personalized curriculum roadmaps and daily revision schedules.</li>
          <li>Grounding preparation blueprints and resume gap analyses in verified facts without fabricating experience.</li>
          <li>Enforcing feature gates and usage limits according to your active plan.</li>
          <li>Preventing account takeovers, brute-force attacks, and automated API abuse.</li>
          <li>Auditing administrative actions and maintaining system reliability.</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>4. AI Processing and Sensitive Data Policy</h2>
        <p>
          Prep includes optional AI enrichment features (such as tutor explanations, draft polish, and mock interview rephrasing). Our data policy enforces strict boundaries:
        </p>
        <ul>
          <li>
            <strong>Bring-Your-Own-Key (BYOK):</strong> Learners may supply their own API keys (e.g., Groq, OpenAI). Learner keys are encrypted at rest with AES-256 and sent strictly to the designated provider for that learner&rsquo;s requests.
          </li>
          <li>
            <strong>Sensitive Feature Isolation:</strong> Features marked sensitive (resume insights, interview feedback, application strategy narratives) are sent to at most one allow-listed provider and never cascaded across multiple providers.
          </li>
          <li>
            <strong>No Raw Resume Dumping:</strong> Where AI assistance is used on resume data, structured facts (skills, titles, years) are sent; full raw documents are never used for third-party model training.
          </li>
          <li>
            <strong>Audit Logging Without Prompts:</strong> Our usage log records only timestamps, token counts, error codes, and feature keys; prompt text and completions are never stored in the administrative audit log.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>5. Data Storage, Security, and Retention</h2>
        <p>
          Your data is stored in isolated PostgreSQL databases with TLS encryption in transit and encrypted disks at rest. Uploaded resume files are stored in private database storage scoped strictly to your authenticated account ID.
        </p>
        <p>
          We retain active account data as long as your account exists. If an account is inactive or deleted, data is purged according to our Data Controls and Deletion policy.
        </p>
      </section>

      <section className="legal-section">
        <h2>6. Third-Party Service Providers</h2>
        <p>We engage trusted third-party sub-processors solely to provide core infrastructure:</p>
        <ul>
          <li>
            <strong>Payment Processing:</strong> Razorpay Software Private Limited for payment collection, invoice generation, and webhook notifications.
          </li>
          <li>
            <strong>Cloud Hosting &amp; Compute:</strong> Vercel Inc. and PostgreSQL Cloud Provider for hosting, serverless functions, and database storage.
          </li>
          <li>
            <strong>Transactional Email:</strong> Transactional mail infrastructure (such as Resend or SMTP provider) for account confirmation and security notifications.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>7. Your Rights and Data Controls</h2>
        <p>
          You have the right to access, inspect, export, and delete your data at any time. For self-service controls, see our dedicated <a href="/data-deletion" className="text-primary underline">Data Controls and Deletion Guide</a>.
        </p>
        <p>
          To exercise statutory rights under applicable data protection laws, contact our Grievance Officer below.
        </p>
      </section>

      <section className="legal-section">
        <h2>8. Grievance Officer and Inquiries</h2>
        <p>
          In accordance with the Information Technology Act, 2000 and Digital Personal Data Protection Act, 2023, the details of our Grievance Officer are:
        </p>
        <div className="legal-callout">
          <p><strong>Designation:</strong> Grievance &amp; Data Protection Officer</p>
          <p><strong>Entity:</strong> Evolw Technologies</p>
          <p><strong>Email:</strong> <a href="mailto:privacy@evolw.in" className="text-primary underline">privacy@evolw.in</a></p>
          <p><strong>Address:</strong> Evolw Technologies, Bengaluru, Karnataka, India</p>
        </div>
      </section>
    </LegalPageLayout>
  )
}
